name: Create Release

on:
  workflow_dispatch:
    inputs:
      package-name:
        type: string
        description: Package name
        required: true
      version:
        type: string
        description: Package version
        required: true
      type:
        type: string
        description: Package type (api or sdk)
        required: false
        enum: [api, sdk]

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_NAME="${{ inputs.package-name }}"
          
          BASE_NAME="${RELEASE_NAME#@api-client-sdk-streamline-sample/}"
          API_BASE="${BASE_NAME%-client}"
          
          DISPLAY_NAME="$(echo "${API_BASE%-api}" | sed 's/-([^-]*)$/\1 /g' | awk '{for(i=1;i<=NF;i++)sub(/./,toupper(substr($i,1,1)),$i)}') API"
          
          SWAGGER_URL="https://app.swaggerhub.com/apis/junjie.wu/sample-${API_BASE}/${{ inputs.version }}"
          
          if [[ "${{ inputs.type }}" == "api" ]]; then
            NOTES="## ${{ inputs.package-name }} v${{ inputs.version }}

            This API version is ready for:
            - Pushing the OpenAPI specification to SwaggerHub
            - Generating and publishing the client SDK package
            
            After pushing the specification, it will be available at:
            📄 [@api-client-sdk-streamline-sample | ${DISPLAY_NAME}](${SWAGGER_URL})
            
            After generating and publishing the SDK, the NPM package will be available at:
            📦 [@api-client-sdk-streamline-sample/${API_BASE}-client](https://www.npmjs.com/package/@api-client-sdk-streamline-sample/${API_BASE}-client)"
          elif [[ "${{ inputs.type }}" == "sdk" ]]; then
            NOTES="## ${{ inputs.package-name }} v${{ inputs.version }}

            NPM Package: 
            📦 [${{ inputs.package-name }}](https://www.npmjs.com/package/${{ inputs.package-name }})
            
            Generated from the corresponding OpenAPI specification:
            📄 [@api-client-sdk-streamline-sample | ${DISPLAY_NAME}](${SWAGGER_URL})"
          fi

          gh release create "v${{ inputs.version }}" \
            --title "${{ inputs.package-name }} v${{ inputs.version }}" \
            --notes "$NOTES"
